[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "423HDGsdSEMLnuPXsggRY2d3YHLGw9ijtAczh3pkCkAs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-depin = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/depin_test.ts"
