apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decloud-backend-cert
  namespace: decloud
spec:
  secretName: decloud-backend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.decloud.krishdev.xyz
  dnsNames:
  - api.decloud.krishdev.xyz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decloud-ws-relayer-cert
  namespace: decloud
spec:
  secretName: decloud-ws-relayer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wss.decloud.krishdev.xyz
  dnsNames:
  - wss.decloud.krishdev.xyz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decloud-depin-ws-relayer-cert
  namespace: decloud
spec:
  secretName: decloud-depin-ws-relayer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wss.depin.decloud.krishdev.xyz
  dnsNames:
  - wss.depin.decloud.krishdev.xyz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: decloud-depin-worker-cert
  namespace: decloud
spec:
  secretName: decloud-depin-worker-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api.depin.decloud.krishdev.xyz
  dnsNames:
  - api.depin.decloud.krishdev.xyz